# Generated by Django 4.1.4 on 2023-01-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=1000)),
                ("answer", models.TextField()),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
