# Generated by Django 4.1.4 on 2023-01-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard", name="question", field=models.TextField(),
        ),
    ]
